
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const REG_ACTION = 'REG_ACTION';
export const LOGINFAIL_ACTION = 'LOGINFAIL_ACTION';
export const FAILREG_ACTION = 'FAILREG_ACTION';
export const LOGOUTFAIL_ACTION = 'LOGOUTFAIL_ACTION';
export const AUTH_ACTION = 'AUTH_ACTION';
